[package]
name = "fed-truth-finder"
version = "0.1.0"
authors = ["fgh1999 <fanguanghong1999@163.com>"]
edition = "2018"

[[bin]]
name = "tls-client-auth-server"
path = "src/tls_client_auth/server.rs"

[[bin]]
name = "tls-client-auth-client"
path = "src/tls_client_auth/client.rs"

[dependencies]
tonic = { version = "^0.3", features = ["tls"]}
prost = "^0.6"
tokio = { version = "^0.2", features = ["full"]}
futures = "^0.3"
dashmap = "^3.11"
async-stream = "^0.3"

[build-dependencies]
tonic-build = { version = "^0.3", features = ["prost"]}
